### PR TITLE
Declare Python 3 support

### PR DESCRIPTION
**Pull request by niklasf**
Python 3 is working just fine. Let's declare that and run automated tests for it.

### CODE REVIEW

**Comment by jfhbrook** [comment]
Does travis support python? Having that sanity check in place sounds like a good idea. I should look into that.

**Comment by niklasf** [comment]
Yeah, you can setup a whole bunch of Python versions as a test matrix. See patch and [docs](http://docs.travis-ci.com/user/languages/python/#Choosing-Python-versions-to-test-against).

**Comment by jfhbrook** [comment]
Oh word, I already have this set up with travis. XD And you added the versions to the tavis.yaml file I forgot I already made.

Cool.

**Comment by jfhbrook** [comment]
lgtm, thanks

**Pull request merged**
