### PR TITLE
Add wheel creation to package/upload scheme

### PR DESCRIPTION
**Pull request by gappleto97**
Hopefully resolving #34 along the way

### CODE REVIEW

**Comment by jfhbrook** [comment]
Yeah alright. I don't think this'll do anything for #34 (asking around, it sounds like pypi may be having cert issues for others), but googling suggests this is reasonable regardless.

**Comment by gappleto97** [comment]
Yeah, I'm skeptical too, but I'm also out of other ideas when it comes to how to fix the problem.

Plus the community seems to like wheels anyhow.

**Comment by jfhbrook** [comment]
alright well 3.0.3 has a universal wheel, so uhh, good luck

**Comment by gappleto97** [comment]
Thanks. I think I'll need it.

**Pull request merged**
