### PR TITLE
Enable being dumped via pickle & similar

### PR DESCRIPTION
**Pull request by LivInTheLookingGlass**

### CODE REVIEW

**Comment by jfhbrook** [comment]
Looks like some test/lint failures, but in the meantime: what the heck is motivating this change??

**Comment by LivInTheLookingGlass** [comment]
I'm running a bot to manage prediction markets on manifold.markets, and it would be  great if I can load them into my database. The use case is for things like leaving a comment on market resolution as to why it was resolved that way

I implemented a hacky version of this in my code, and just now realized I could adapt this upstream so that someone else might not have that problem

**Comment by LivInTheLookingGlass** [comment]
There probably are better ways to implement the larger goal, but making this serializable was surprisingly simple. I'd already had to  muck around with that to ensure logger objects and credentials don't get captured

**Comment by LivInTheLookingGlass** [comment]
Just wanted to bump in case this was forgotten about. The tests do pass now

**Pull request merged**
