### PR TITLE
Bump trio* deps

### PR DESCRIPTION
**Pull request by decentral1se**
Some dependency updates coming down the tubes...

```
➜  pyee (bump-trio) ✔ grep -iR "trio==" .
./requirements_dev.txt:pytest-trio==0.6.0
./requirements_dev.txt:trio==0.15.1
./requirements_dev_py35.txt:trio==0.15.1
./environment.yml:    - pytest-trio==0.6.0
./environment.yml:    - trio==0.15.1
```

### CODE REVIEW

**Comment by decentral1se** [comment]
CI failure: https://travis-ci.org/github/jfhbrook/pyee/jobs/690008718. Seems that this happened https://github.com/python-trio/trio/issues/75 (py35 support dropped). How do you want to handle that here @jfhbrook? Can try take care of it.

**Comment by decentral1se** [comment]
Quick-fix being 1. don't upgrade :+1:  2. `trio <= 0.14`

**Comment by jfhbrook** [comment]
Just seeing this. Sorry it took a month, I completely missed the notification and saw this on accident.

I'm OK disabling trio tests for python versions less than what it supports.

**Comment by jfhbrook** [comment]
Addressed this in #74.

**Pull request closed without merging**
