### PR TITLE
Include license in PyPI package

### PR DESCRIPTION
**Pull request by polyzen**

### CODE REVIEW

**Comment by jfhbrook** [comment]
Oh nice!

Would you mind adding yourself to https://github.com/jfhbrook/pyee/blob/master/CONTRIBUTORS.rst ?

**Comment by polyzen** [comment]
Done 👍

**Comment by jfhbrook** [comment]
Very nice. How pressing is this to get out the door? I can try to get a patch release out later this week but can try to move faster if you're blocked on something.

**Comment by polyzen** [comment]
No rush.

**Comment by jfhbrook** [comment]
Good good. Thanks again!

**Pull request merged**
